### ISSUE TITLE
Feedback for “Inferencing”

### ISSUE THREAD

**Issue by ETCore7** [IAHispano/Applio-Website#11]
Thank you for your manual, but I am completely lost at step 1, "Select a model" since there is no model. There is a download tab with some models. I selected Titan, a progress bar appeared "downloading", and then nothing. Only later a popup appeared, apparently something was downloaded in the background. Back to the first tab, "Select model" is still empty.

A short 'getting started' tutorial for absolute beginners would be welcome.

**Comment by AznamirWoW** [comment]
Models used for inteferencing are RVC voice models. Right now the model search and download withing Applio is broken, so find one you want manually on weights.gg, voice-models.com, applio.org/models, download, unzip into a folder under logs.

The model you tried to download (Titan) is a pretrained model used for training only.

**Comment by bygimenez** [comment]
> Thank you for your manual, but I am completely lost at step 1, "Select a model" since there is no model. There is a download tab with some models. I selected Titan, a progress bar appeared "downloading", and then nothing. Only later a popup appeared, apparently something was downloaded in the background. Back to the first tab, "Select model" is still empty.
> 
> A short 'getting started' tutorial for absolute beginners would be welcome.

We have all the guides you need in [our docs](https://docs.applio.org). I recommend you start with [this section](https://docs.applio.org/beginners/ai-cover).

**Comment by bygimenez** [comment]
> Models used for inteferencing are RVC voice models. Right now the model search and download withing Applio is broken, so find one you want manually on weights.gg, voice-models.com, applio.org/models, download, unzip into a folder under logs.
> 
> The model you tried to download (Titan) is a pretrained model used for training only.

Downloading and searching for models in Applio should work, if you think it doesn't, please [report it in the official repository](https://github.com/IAHispano/Applio/issues).
