### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brcisna** [IAHispano/Applio-Website#8]
**Describe the bug**
API Keys missing

**To Reproduce**
1. launch the Applio website with ,,,
2. npm run dev
3. a webpage partial appears  with ,,,
4. <We have not found any API KEYS, we understand that you are in development mode so you will not have errors but you will not be able to access database functionality.
 ⨯ node_modules/@supabase/auth-helpers-nextjs/dist/index.js (47:0) @ createClientComponentClient
 ⨯ Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
    at AvatarMobile (./components/navbar/navbar-avatar-mobile.tsx:19:112)
null>

**Expected behavior**
the website shoul appear as expected 

**Assets**

![Applio-WEB](https://github.com/IAHispano/Applio-Website/assets/47399290/f4b0ab89-7f75-43fc-9c99-bea4cd0027c5)

**Desktop (please complete the following information):**
 - OS: Linux Debian 12 Bookworm 
 - Browser Chrome

**Additional context**
None

**Comment by blaise-tk** [comment]
In some sections of the web a supabase private key is required to connect the web to the database. If you have in mind to make any changes, we can chat and provide you with the keys.

**Comment by bygimenez** [comment]
> **Describe the bug** API Keys missing
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. launch the Applio website with ,,,
> 2. npm run dev
> 3. a webpage partial appears  with ,,,
> 4. <We have not found any API KEYS, we understand that you are in development mode so you will not have errors but you will not be able to access database functionality.
>    ⨯ node_modules/@supabase/auth-helpers-nextjs/dist/index.js (47:0) @ createClientComponentClient
>    ⨯ Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
>    at AvatarMobile (./components/navbar/navbar-avatar-mobile.tsx:19:112)
>    null>
> 
> **Expected behavior** the website shoul appear as expected
> 
> **Assets**
> 
> ![Applio-WEB](https://private-user-images.githubusercontent.com/47399290/311772497-f4b0ab89-7f75-43fc-9c99-bea4cd0027c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODA5OTEsIm5iZiI6MTcxMDE4MDY5MSwicGF0aCI6Ii80NzM5OTI5MC8zMTE3NzI0OTctZjRiMGFiODktN2Y3NS00M2ZjLTljOTktYmVhNGNkMDAyN2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE4MTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNjFlNjI3MzM0MGExMDVhY2M0Y2U1OTg2OTRhYmFmMTExNzRkMGRlNTZlNmIwYzVkZDE0MzA5MWRiN2MyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJi-i7nwXVrvHMG-t53uQYRwksQlSF2Xfp7n0rn9O4Y)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Linux Debian 12 Bookworm
> * Browser Chrome
> 
> **Additional context** None

There is **no error here**, to access the parts that are connected to the database **you need the supabase API KEYS** (**they are private** obviously).
